# Tensors
1. 张量的定义：
- 张量类似于NumPy 的 ndarray，但具备更多的功能。
- 它是PyTorch 中的核心数据结构，用来表示数据和参数。
2. 与 NumPy 的区别：
- GPU 加速：张量可以在GPU 或其他硬件加速器上运行，这使得深度学习的计算更高效。
- 内存共享：PyTorch 张量和 NumPy 数组可以共享内存，无需复制数据，支持高效的数据转换。
3. 自动求导：
- 张量支持自动微分，这对训练神经网络中的反向传播非常重要。
4. API 易用性：
- PyTorch 的张量 API 与 NumPy 的 ndarray API 非常相似，如果熟悉 NumPy，则使用张量会感觉非常自然。

总结一句话：
张量（Tensor）是**支持自动求导和 GPU 加速的多维数组**，它是 PyTorch 中的**核心数据结构**，用于表示**模型的输入、输出和参数**。

In [1]:
import torch
import numpy as np

## Initializing a Tensor
Tensor 可以通过很多种方式进行初始化

### 1. Directly from data
由嵌套列表转换为 tensor，Pytorch 会自动推测数据类型

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f'x_data:\n{x_data}\n数据类型为:\n{x_data.dtype}')

x_data:
tensor([[1, 2],
        [3, 4]])
数据类型为:
torch.int64


### 2. From a Numpy array
由 Numpy array 转换为 Tensor，它们之间是共享内存的，改变一个也会改变另外一个。

可参考 [Bridge with Numpy](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f'Numpy array:\n{np_array}\n转换为 Tensor 后:\n{x_np}')

# 改变 np.array
np_array[0] = [7,8]

print(f'\n改变后的 Numpy array:\n{np_array}\n观察 x_np 是否也会随之改变:\n{x_np}')

Numpy array:
[[1 2]
 [3 4]]
转换为 Tensor 后:
tensor([[1, 2],
        [3, 4]])

改变后的 Numpy array:
[[7 8]
 [3 4]]
观察 x_np 是否也会随之改变:
tensor([[7, 8],
        [3, 4]])


### 3. From another tensor
- [torch.ones](https://pytorch.org/docs/stable/generated/torch.ones.html#torch.ones) 好理解，张量中的值全都是 1
- [torch.rand](https://pytorch.org/docs/stable/generated/torch.rand.html#torch.rand) 生成的张量中的数值是在[0,1)区间内的随机数

In [4]:
x_ones = torch.ones_like(x_data) # 保留 x_data 的属性
print(f'全 1 Tensor: \n{x_ones}\n')

x_rand = torch.rand_like(x_data, dtype = torch.float) # 覆写 x_data 的数据类型
print(f'随机 Tensor: \n{x_rand}\n')

全 1 Tensor: 
tensor([[1, 1],
        [1, 1]])

随机 Tensor: 
tensor([[0.6769, 0.2231],
        [0.5869, 0.5095]])



### 4. With random or constant values
`shape`要用元组的形式来表示 tensor 的维度

In [5]:
shape = (2, 3, 5)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'以下生成形状为 {shape} 的各类型 tensor！')
print(f'随机 tensor: \n{rand_tensor}\n')
print(f'全 1 tensor: \n{ones_tensor}\n')
print(f'全 0 tensor: \n{zeros_tensor}\n')

以下生成形状为 (2, 3, 5) 的各类型 tensor！
随机 tensor: 
tensor([[[0.5234, 0.8620, 0.1286, 0.2433, 0.0251],
         [0.6767, 0.1613, 0.9619, 0.0538, 0.4775],
         [0.2669, 0.1617, 0.1155, 0.6800, 0.6925]],

        [[0.7333, 0.8868, 0.3315, 0.6481, 0.3191],
         [0.1769, 0.1584, 0.5095, 0.7811, 0.8386],
         [0.2861, 0.6514, 0.1578, 0.5741, 0.6747]]])

全 1 tensor: 
tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

全 0 tensor: 
tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])



---
## Attributes of a Tensor
一个 tensor 拥有的特征:
- shape 形状，即维度
- dtype 数据类型
- device 存储在什么硬件上


In [6]:
tensor = torch.rand(3, 4)
print(f'tensor 的形状 {tensor.shape}')
print(f'tensor 的数据类型 {tensor.dtype}')
print(f'tensor 的存储设备 {tensor.device}')

tensor 的形状 torch.Size([3, 4])
tensor 的数据类型 torch.float32
tensor 的存储设备 cpu


---
## Operations on Tensor
PyTorch 支持丰富的张量操作，这些操作可以在GPU 上高效运行，但默认的张量是在 CPU 上创建的。要在 GPU 上操作张量，需要使用 .to(device) 方法将其移动到 GPU，但设备间的大量数据传输会消耗时间和内存，应尽量避免频繁切换设备。

In [7]:
# 如果存在 GPU 设备的话，可以将 tensor 转移到 gpu 上
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
else:
    print('并没有可用的 gpu')

并没有可用的 gpu


### standard numpy-like indexing and slicing

In [8]:
tensor = torch.randint(0,10, (4,4))
print(f'tensor:\n{tensor}')
print(f'第一行: {tensor[0]}')
print(f'第一列: {tensor[:, 0]}')
print(f'最后一列: {tensor[:, -1]}')
tensor[:, 1] = 0
print(tensor)

tensor:
tensor([[0, 3, 0, 1],
        [7, 2, 6, 2],
        [8, 7, 7, 8],
        [3, 7, 0, 7]])
第一行: tensor([0, 3, 0, 1])
第一列: tensor([0, 7, 8, 3])
最后一列: tensor([1, 2, 8, 7])
tensor([[0, 0, 0, 1],
        [7, 0, 6, 2],
        [8, 0, 7, 8],
        [3, 0, 0, 7]])


### Joining tensors
连接 tensor 
如何理解参数 dim?
dim = 1 可以理解为 在第二个维度上连接，结果是第二个维度的长度增加。在 2 维 tensor 中，就是按列连接

In [9]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim = 0)
print(t2)

tensor([[0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1],
        [7, 0, 6, 2, 7, 0, 6, 2, 7, 0, 6, 2],
        [8, 0, 7, 8, 8, 0, 7, 8, 8, 0, 7, 8],
        [3, 0, 0, 7, 3, 0, 0, 7, 3, 0, 0, 7]])
tensor([[0, 0, 0, 1],
        [7, 0, 6, 2],
        [8, 0, 7, 8],
        [3, 0, 0, 7],
        [0, 0, 0, 1],
        [7, 0, 6, 2],
        [8, 0, 7, 8],
        [3, 0, 0, 7],
        [0, 0, 0, 1],
        [7, 0, 6, 2],
        [8, 0, 7, 8],
        [3, 0, 0, 7]])


### Arithmetic operation

In [10]:
tensor = torch.ones(4, 4)
tensor[:,2] = 2
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)
print(y1, '\n\n', y2, '\n\n', y3)

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]]) 

 tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]]) 

 tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.],
        [7., 7., 7., 7.]])


In [11]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

print(z1, '\n\n', z2, '\n\n', z3)

tensor([[1., 1., 4., 1.],
        [1., 1., 4., 1.],
        [1., 1., 4., 1.],
        [1., 1., 4., 1.]]) 

 tensor([[1., 1., 4., 1.],
        [1., 1., 4., 1.],
        [1., 1., 4., 1.],
        [1., 1., 4., 1.]]) 

 tensor([[1., 1., 4., 1.],
        [1., 1., 4., 1.],
        [1., 1., 4., 1.],
        [1., 1., 4., 1.]])


### Single-element tensors
如果有一个单元素的 tensor （通常是整合一个 tensor 中所有元素得来的），可以通过 `item()` 的方法将其转换为 python 的 `numerical value`

In [12]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

20.0 <class 'float'>


### In-place operation
在中文中，把这类操作叫做原地操作，在同一个内存地址上改变元素的值。这类操作都有一个`_`后缀

In [13]:
print(f'{tensor} \n')
tensor.add_(5)
print(tensor)

tensor([[1., 1., 2., 1.],
        [1., 1., 2., 1.],
        [1., 1., 2., 1.],
        [1., 1., 2., 1.]]) 

tensor([[6., 6., 7., 6.],
        [6., 6., 7., 6.],
        [6., 6., 7., 6.],
        [6., 6., 7., 6.]])
